### ISSUE TITLE
2nd start of Monitored Run fails

### ISSUE THREAD

**Issue by jws01** [EliasGroll/pbi#1]
Hello,
1.) thx for the program!
2.) 2nd start of a programm for BS1 with some GOSUBs fails with:
...
[Warn, line 147]There is a label called "Steuern
[Warning]A parsed instance didn't return a initialized command
[Warn]The program is very long[Error, parse]There are only 16 calls of "GOSUB" allowed
...
[End of file, 0 milliseconds, 0 instructions]

Workaraound:
Terminate pbi, restart pbi, load program *.bs1, monitored run

**Comment by eliasgroll** [comment]
Thanks for your report.

It has been a threading problem - we are currently working on it. Could you post your code so we can test it?

**Comment by jws01** [comment]
Hello,

see attached file for code.

1st start:

PiBasic VM [Version 2.15] 

 by Elias Groll, Jonas Reichmann.

[Execute, D:\Users\adminjs\Documents-JS-\Meine Hobbies\BasicStamp\NWT_Projekt_Auto\Aufgabe_03_06.05_JS03_dbg.bs1][Warn, line 60]There is a label called "Start

[Warn, line 66]There is a label called "Suche_Wechsel1

[Warn, line 74]There is a label called "Fahren

[Warn, line 82]There is a label called "Bin_Rechts

[Warn, line 88]There is a label called "Bin_Links

[Warn, line 96]There is a label called "Grundstellung

[Warn, line 110]There is a label called "Vorwaerts

[Warn, line 121]There is a label called "Stop

[Warn, line 128]There is a label called "H_Messung

[Warn, line 132]There is a label called "Hell

[Warn, line 136]There is a label called "Dunkel

[Warn, line 142]There is a label called "Lenken

[Warn, line 147]There is a label called "Steuern

[Warn]The program is very long

[Info]Activating additional information[Info]Referencing B0 with dl

[Info]Referencing 20 with PDauer

[Info]Referencing 6 with Lenkung

[Info]DIRLenkung is now set to 1(OUTPUT)

[Info]Referencing 150 with Geradeaus

[Info]Referencing 190 with NachLinks

[Info]Referencing 110 with NachRechts

[Info]Referencing 20 with LDauerR

[Info]Referencing 15 with LDauerL

[Info]Referencing B3 with lDauer

[Info]Referencing B4 with lRichtung

[Info]Referencing 3 with AnzBefehle

[Info]Referencing 0 with X

[Info]Referencing 1 with Y

[Info]DIRX is now set to 1(OUTPUT)

[Info]DIRY is now set to 1(OUTPUT)

[Info]Referencing 100 with Langsam

[Info]Referencing 20 with MDauer

[Info]Referencing 7 with HSensor

[Info]Referencing 100 with HGrenze

[Info]Referencing 125 with SFactor

[Info]Referencing B1 with hWert

[Info]Referencing B2 with hWertAlt

[Info]Referencing 50 with Weisz

[Info]Referencing 150 with Schwarz

[Info]Execution reached a label called "Start"

[Info]Input a valid command to be evaluated and executed seperately

[Breakpoint, line 61]

END

[Input]accepted: [Info]Terminating execution

[End of file, 16396 milliseconds, 29 instructions]

Output 2nd start:

PiBasic VM [Version 2.15] 

 by Elias Groll, Jonas Reichmann.

[Execute, D:\Users\adminjs\Documents-JS-\Meine Hobbies\BasicStamp\NWT_Projekt_Auto\Aufgabe_03_06.05_JS03_dbg.bs1][Warn, line 60]There is a label called "Start

[Warn, line 66]There is a label called "Suche_Wechsel1

[Warn, line 74]There is a label called "Fahren

[Warning]A parsed instance didn't return a initialized command

[Warn, line 82]There is a label called "Bin_Rechts

[Warning]A parsed instance didn't return a initialized command

[Warn, line 88]There is a label called "Bin_Links

[Warning]A parsed instance didn't return a initialized command

[Warn, line 96]There is a label called "Grundstellung

[Warning]A parsed instance didn't return a initialized command

[Warn, line 110]There is a label called "Vorwaerts

[Warn, line 121]There is a label called "Stop

[Warn, line 128]There is a label called "H_Messung

[Warn, line 132]There is a label called "Hell

[Warn, line 136]There is a label called "Dunkel

[Warn, line 142]There is a label called "Lenken

[Warn, line 147]There is a label called "Steuern

[Warning]A parsed instance didn't return a initialized command

[Warn]The program is very long

[Error, parse]There are only 16 calls of "GOSUB" allowed

[Error, parse]There are only 16 calls of "GOSUB" allowed

[Error, parse]There are only 16 calls of "GOSUB" allowed

[Error, parse]There are only 16 calls of "GOSUB" allowed

[Error, parse]There are only 16 calls of "GOSUB" allowed

[End of file, 0 milliseconds, 0 instructions]

Von: Elias Groll [mailto:notifications@github.com] 
Gesendet: Dienstag, 10. Mai 2016 12:25
An: EliasGroll/pbi
Cc: jws01; State change
Betreff: Re: [EliasGroll/pbi] 2nd start of Monitored Run fails (#1)

Thanks for your report.

It has been a threading problem - we are currently working on it. Could you post your code so we can test it?
