### ISSUE TITLE
DEBUG with unknown/wrongwritten Variable terminates debug session

### ISSUE THREAD

**Issue by jws01** [EliasGroll/pbi#2]
[Input]continue.. 
[Error, runtime]Unknown variable "IRichtung"
[Error, runtime]"DEBUG" has a bad format

[End of file, 4071209 milliseconds, 383 instructions]

**Comment by eliasgroll** [comment]
Thanks for your report!

An unknown variable in the bs1 is a reference to nothing. We check it at runtime, because our breakpoint statement supports  the declaration of new variables at runtime. Pbi is designed to help you to find errors in your code, so it might me more strict than the bs1 parser.
