### ISSUE TITLE
Analog I/O commands POT and PWM not supported

### ISSUE THREAD

**Issue by jws01** [EliasGroll/pbi#3]
POT Pin, Scale, Variable
PWM Pin, Duty, Duration
are unfortunately not allowed in pbi
It would be good if they are at least tolerated.
Otherwise each occurance has to be commented out manually.

**Comment by eliasgroll** [comment]
Thank you for the report!

Since we do not support analog simulation of the bs1, these commands have been excluded. The next release will tolerate them, create output but not simulate them. Analog simulation may be included in a later release.

**Comment by eliasgroll** [comment]
The project will not be developed further.
